
#pragma once

//定义主界面用到的消息
#define WM_DLG_PRINTLOG			(WM_USER + 1)
#define WM_MAINDLG_SETTYPETAB	(WM_USER + 2)
#define WM_TRACEDLG_STOPTRACE	(WM_USER + 3)
#define WM_DLG_GETPROCESSFAILED	(WM_USER + 4)

//定义工作线用到的消息
#define WM_WORKER_STARTTRACE	(WM_USER + 100)
#define WM_WORKER_FLUSHTRACE	(WM_USER + 101)
#define WM_WORKER_ISHUNGWINDOW	(WM_USER + 102)
#define WM_WORKER_CHECKIO		(WM_USER + 103)
#define WM_WORKER_CHECKCPU		(WM_USER + 104)
#define WM_WORKER_CHECKMEMORY	(WM_USER + 105)
#define WM_WORKER_CHECKHUNG		(WM_USER + 106)
#define WM_WORKER_LUAERROR		(WM_USER + 107)

//错误码
#define XLDIAGTOOL_SUCC	0	//成功
#define XLDIAGTOOL_FAILED	-1	//失败
#define XLDIAGTOOL_FAILED_HAVEINIT	-2	//已经初始化过
#define XLDIAGTOOL_FAILED_CREATETHREAD	-3	//创建线程失败
#define XLDIAGTOOL_FAILED_INVALIDPARAM	-4	//无效参数
#define XLDIAGTOOL_FAILED_CANNOTFINDPROCESS	-5	//进程不存在
#define XLDIAGTOOL_FAILED_ALREADYSTARTED	-6	//已经开始搜集
#define XLDIAGTOOL_FAILED_TRACENOTSTART	-7	//还没开始搜集日志
#define XLDIAGTOOL_FAILED_TRACESTARTING	-8	//搜集日志正在开始
#define XLDIAGTOOL_FAILED_TRACESTOPPING	-9	//搜集日志正在停止
#define XLDIAGTOOL_FAILED_TRACESTOPPED	-10	//搜集日志已经停止
#define XLDIAGTOOL_FAILED_TRACEFLUSHING	-11	//正在搜集日志
#define XLDIAGTOOL_FAILED_HAVENOTINIT	-12	//未初始化
#define XLDIAGTOOL_FAILED_WRITEFILE		-13	//写入文件失败
